# TODO research config file

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coder Log
email: ackoujens@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My own little place of coding feats and wonders.
baseurl: "/coder-log" # the subpath of your site, e.g. /blog
url: "http://ackoujens.github.io" # the base hostname & protocol for your site
twitter_username: ackoujens
github_username:  ackoujens

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  #style: :compressed
theme: minima

# Global link appearance
permalink: /:title

# Limit posts to parse
lsi: false

# Disable custom plugins
safe: false

# Javascript
jsarr:
  - bootstrap.js
  - jquery.js

gems:
  - jekyll-coffeescript
