# Coder Log configuration
title: The Coder Log
email: ackoujens@gmail.com
description: My own little place of coding feats and wonders
baseurl: /coder-log
url: http://ackoujens.github.io
assets: /coder-log/assets

# Social
twitter_username: ackoujens
github_username:  ackoujens

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  #style: :compressed
theme: minima

# Global link appearance
permalink: /:title

# Limit posts to parse
lsi: false

# Disable custom plugins
safe: false

gems:
  - jekyll-coffeescript
